#
# B-Free Project の生成物は GNU Generic PUBLIC LICENSE に従います。
#
# GNU GENERAL PUBLIC LICENSE
# Version 2, June 1991
#
# (C) B-Free Project.
#


all:
	(cd console; make)
	(cd keyboard; make)
	(cd fd765a; make)