#ifndef __BTRON_ERROR_H__
#define __BTRON_ERROR_H__

#define E_OK            (0)
#define E_ADR           (-1)
#define E_PAR           (-2)
#define E_NOSPT         (-3)
#define E_NOSPC         (-4)
#define E_ID            (-5)
#define E_EXS           (-6)
#define E_NOEXS         (-7)
#define E_NOMEM         (-8)
#define E_CTX           (-9)
#define E_SYS           (-10)
#define E_UNF           (-11)
#define E_SZOVR         (-12)
#define E_MPTR          (-13)
#define E_AKEY          (-14)
#define E_MPURG         (-15)
#define E_MRELOC        (-16)
#define E_PPRI          (-17)
#define E_NOPRC         (-18)
#define E_SELF          (-19)
#define E_LEVEL         (-20)
#define E_MINTR         (-21)
#define E_DLT           (-22)
#define E_SEM           (-23)
#define E_NONE          (-24)
#define E_INIT          (-25)
#define E_FNAME         (-26)
#define E_FD            (-27)
#define E_ACCES         (-28)
#define E_PERM          (-29)
#define E_RONLY         (-30)
#define E_PWD           (-31)
#define E_ENDR          (-32)
#define E_REC           (-33)
#define E_NOLNK         (-34)
#define E_LOCK          (-35)
#define E_LIMIT         (-36)
#define E_XFS           (-37)
#define E_NOFS          (-38)
#define E_NODSK         (-39)
#define E_TRON          (-40)
#define E_DD            (-41)
#define E_DEV           (-42)
#define E_BUSY          (-43)
#define E_NODEV         (-44)
#define E_ERDEV         (-45)
#define E_NOMDA         (-46)
#define E_IO            (-47)

#endif /* __BTRON_ERROR_H__ */

